NeoSistem.Trinnk.Management/Controllers/StoreSeoNotificationController.cs
using Trinnk.Entities.Tables.Stores;
using Trinnk.Services.Common;
using Trinnk.Services.Stores;
using Trinnk.Utilities.FormatHelpers;
using NeoSistem.Trinnk.Management.Models;
using NeoSistem.Trinnk.Management.Models.Authentication;
using NeoSistem.Trinnk.Management.Models.Entities;
using NeoSistem.Trinnk.Management.Models.Stores;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace NeoSistem.Trinnk.Management.Controllers
{

    public class StoreSeoNotificationController : BaseController
    {
        IStoreSeoNotificationService _storeSeoNotificationService;
        IStoreService _storeService;
        IConstantService _constantService;

        public StoreSeoNotificationController(IStoreSeoNotificationService storeSeoNotificationService, IStoreService storeService,
            IConstantService constantService)
        {
            _storeSeoNotificationService = storeSeoNotificationService;
            _storeService = storeService;
            _constantService = constantService;
        }
        public ActionResult Index(int storeMainPartyId)
        {
            var entites = new TrinnkEntities();
            var store = _storeService.GetStoreByMainPartyId(storeMainPartyId);
            var storeSeoNotifications = _storeSeoNotificationService.GetStoreSeoNotificationsByStoreMainPartyId(storeMainPartyId).OrderByDescending(x => x.StoreSeoNotificationId);
            List<BaseMemberDescriptionModelItem> baseMemberDescriptions = new List<BaseMemberDescriptionModelItem>();
            foreach (var item in storeSeoNotifications)
            {
                var fromUser = entites.Users.FirstOrDefault(x => x.UserId == item.FromUserId);
                var toUser = entites.Users.FirstOrDefault(x => x.UserId == item.ToUserId);

                baseMemberDescriptions.Add(new BaseMemberDescriptionModelItem
                {
                    Description = FormatHelper.GetMemberDescriptionText(item.Text),
                    FromUserName = fromUser.UserName,
                    ToUserName = toUser.UserName,
                    StoreID = item.StoreMainPartyId,
                    LastDate = item.RemindDate,
                    InputDate = item.CreatedDate,
                    ID = item.StoreSeoNotificationId,
                    Title = item.ConstantId.HasValue ? _constantService.GetConstantByConstantId(item.ConstantId.Value).ConstantName : ""
                });
            }
            StoreSeoNotificationModel model = new StoreSeoNotificationModel();
            model.BaseMemberDescriptionModelItems = baseMemberDescriptions;
            model.StoreName = store.StoreName;
            return View(model);
        }
        public ActionResult Create(int? id, int? storeNotId)
        {
            var model = new StoreSeoNotificationFormModel();

            var entities = new TrinnkEntities();
            var users1 = from u in entities.Users join p in entities.PermissionUsers on u.UserId equals p.UserId join g in entities.UserGroups on p.UserGroupId equals g.UserGroupId where (g.UserGroupId == 21 || g.UserGroupId == 11 || g.UserGroupId == 7 || g.UserGroupId == 18) && u.Active == true select new { u.UserName, u.UserId };
            var storeSeoNotification = new StoreSeoNotification();
            var contstants = _constantService.GetConstantByConstantType(ConstantTypeEnum.SeoDecriptionTitle);
            if (storeNotId.HasValue)
            {
                storeSeoNotification = _storeSeoNotificationService.GetStoreSeoNotificationByStoreSeoNotificationId(storeNotId.Value);
                model.PreviousText = storeSeoNotification.Text;
                model.StoreSeoNotificationId = storeNotId.Value;
                model.StoreMainPartyId = (int)storeSeoNotification.StoreMainPartyId;
                if (!storeSeoNotification.ConstantId.HasValue || storeSeoNotification.ConstantId == 0)
                    model.Titles.Add(new SelectListItem { Text = "Seçiniz", Value = "0" });

                foreach (var item in contstants)
                {
                    if (storeSeoNotification.ConstantId == item.ConstantId)
                    {
                        model.Titles.Add(new SelectListItem { Text = item.ConstantName, Value = item.ConstantId.ToString(), Selected = true });
                    }
                    else
                    {
                        model.Titles.Add(new SelectListItem { Text = item.ConstantName, Value = item.ConstantId.ToString() });
                    }

                }
                model.ToUserId = (int)storeSeoNotification.ToUserId;
                model.ConstantId = storeSeoNotification.ConstantId.HasValue ? storeSeoNotification.ConstantId.Value : (short)0;
            }
            else if (id.HasValue)
            {
                model.StoreMainPartyId = id.Value;
                model.Titles.Add(new SelectListItem { Text = "Seçiniz", Value = "0" });
                foreach (var item in contstants)
                {
                    model.Titles.Add(new SelectListItem { Text = item.ConstantName, Value = item.ConstantId.ToString() });
                }
            }

            foreach (var item in users1.OrderBy(x => x.UserName))
            {
                var element = new SelectListItem
                {
                    Text = item.UserName,
                    Value = item.UserId.ToString()
                };
                if (storeSeoNotification != null && item.UserId == storeSeoNotification.ToUserId)
                {
                    element.Selected = true;
                }

                model.ToUsers.Add(element);
            }


            return View(model);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(StoreSeoNotificationFormModel model, string time)
        {
            if (!string.IsNullOrEmpty(model.Text))
            {
                int year = 0, day = 0, month = 0;
                int hour = 0, minute = 0;
                DateTime lastDate = new DateTime();
                if (model.ConstantId == 0)
                {
                    ModelState.AddModelError("ConstantId", "Lütfen Başlık Seçiniz");
                }
                else
                {
                    if (string.IsNullOrEmpty(model.RemindDate))
                    {
                        model.RemindDate = DateTime.Now.Date.ToString("dd.MM.yyyy");
                    }
                    else
                    {
                        string[] time1 = model.RemindDate.ToString().Split('.');
                        year = Convert.ToInt32(time1[2]);
                        month = Convert.ToInt32(time1[1]);
                        day = Convert.ToInt32(time1[0]);
                    }
                    if (!string.IsNullOrEmpty(time))
                    {
                        hour = Convert.ToInt32(time.Split(':')[0]);
                        minute = Convert.ToInt32(time.Split(':')[1]);
                    }
                    else
                    {
                        hour = DateTime.Now.Hour;
                        minute = DateTime.Now.Minute + 1;
                        if (day != DateTime.Now.Day)
                        {
                            hour = 8;
                            minute = 30;
                        }
                    }
                    lastDate = new DateTime(year, month, day, hour, minute, 0);
                    if (lastDate > DateTime.Now)
                    {

                        if (model.StoreSeoNotificationId != 0)
                        {
                            var storeSeoNotificationPrev = _storeSeoNotificationService.GetStoreSeoNotificationByStoreSeoNotificationId(model.StoreSeoNotificationId);
                            storeSeoNotificationPrev.RemindDate = lastDate;
                            storeSeoNotificationPrev.Status = 0;
                            storeSeoNotificationPrev.ToUserId = Convert.ToByte(model.ToUserId);
                            if (storeSeoNotificationPrev.ConstantId == model.ConstantId)
                            {
                                storeSeoNotificationPrev.Text = "<span style='color:#31c854; '>" + DateTime.Now + "</span>-" + model.Text + "-" + "<span style='color:#44000d; font-weight:600;'>" + CurrentUserModel.CurrentManagement.UserName + "</span>" + "~" + storeSeoNotificationPrev.Text;
                                _storeSeoNotificationService.UpdateStoreSeoNotification(storeSeoNotificationPrev);
                            }
                            else
                            {
                                string text = "<span style='color:#31c854; '>" + DateTime.Now + "</span>-" + model.Text + "<span style='color:#44000d'>" + CurrentUserModel.CurrentManagement.UserName + "</span>";

                                var storeSeoNotification = new StoreSeoNotification
                                {
                                    CreatedDate = DateTime.Now,
                                    RemindDate = lastDate,
                                    FromUserId = CurrentUserModel.CurrentManagement.UserId,
                                    ToUserId = Convert.ToByte(model.ToUserId),
                                    Status = 0,
                                    StoreMainPartyId = model.StoreMainPartyId,
                                    ConstantId = model.ConstantId,
                                    Text = text
                                };
                                _storeSeoNotificationService.InsertStoreSeoNotification(storeSeoNotification);
                            }

                        }
                        else
                        {
                            string text = "<span style='color:#31c854; '>" + DateTime.Now + "</span>-" + model.Text + "<span style='color:#44000d'>" + CurrentUserModel.CurrentManagement.UserName + "</span>";

NeoSistem.Trinnk.Management/Views/StoreSeoNotification/AllNotification.cshtml
@model NeoSistem.Trinnk.Management.Models.Stores.StoreSeoNotificationModel

@section TitleContent {

    Firma Seo Bildirimleri

}


    <div style="margin-top: 20px;">
        <h2 style="float: left;">Firma Seo Bildirimleri
        </h2>
    </div>
    <div style="width: 100%; margin: 0 auto;">
        <table cellpadding="5" cellspacing="0" class="TableList" style="width: 100%; margin-top: 5px">
            <thead>
                <tr>
                    <td class="Header">Firma Adı</td>
                    <td class="Header">Başlık</td>
                    <td class="Header">İçerik</td>
                    <td class="Header">İşlem Tarihi</td>
                    <td class="Header">Hatırlatma Tarihi</td>
                    <td class="Header">Atayan</td>
                    <td class="Header">Atanan</td>

                    <td class="Header HeaderEnd">Araçlar</td>
                </tr>
            </thead>
            <tbody>
                @{int row = 0; }
                @foreach (var itemMemberDesc in Model.BaseMemberDescriptionModelItems.ToList())
                    {
                        string backgroundColor = "";
                        var compateFisrst = DateTime.Compare(itemMemberDesc.LastDate.Value.AddMinutes(45), DateTime.Now);
              
                        if (compateFisrst > 0 && itemMemberDesc.IsFirst)
                        {
                            backgroundColor = "background-color:#f97b7b";
                            if (itemMemberDesc.LastDate.Value.AddMinutes(30) > DateTime.Now)
                            {
                                backgroundColor = "background-color:#f1dc65";
                            }
                        }
                        else if ( itemMemberDesc.IsFirst)
                        {
                            backgroundColor = "background-color:#f97b7b";
                        }

                
                <tr id="@("row"+itemMemberDesc.ID)" class="@(row % 2 == 0 ? "Row" : "RowAlternate")" style=" @backgroundColor">
                    <td class="Cell"><a href="/Store/EditStore/@itemMemberDesc.StoreID">@itemMemberDesc.StoreName</a></td>
                    <td class="Cell">@itemMemberDesc.Title</td>
                    <td class="Cell" style="font-size: 15px;">@if (itemMemberDesc.Description != null)
                                                                  { 
                        @Html.Raw(itemMemberDesc.Description)
                         }
                        
                    </td>
                    <td class="Cell">@if (itemMemberDesc.InputDate != null)
                                         {
                                             string[] Inputdate = itemMemberDesc.InputDate.ToString().Split(' ');
                                             @Inputdate[0]
                                             <font style='color:#C5D5DD'>@Inputdate[1]</font>
                                         }</td>
                    <td class="Cell">@if (itemMemberDesc.LastDate.ToDateTime().Date >= DateTime.Now.Date)
                                         {
                                             string[] lastDate = itemMemberDesc.LastDate.ToString().Split(' ');
                                             @lastDate[0]
                                             <font style='color:#9d0825'>@lastDate[1]</font>
                                         } </td>
                    <td class="Cell" style="background-color: #2776e5; color: #fff">@itemMemberDesc.FromUserName</td>
                    <td class="Cell" style="background-color: #31c854; color: #fff">
                        @itemMemberDesc.ToUserName
                    </td>
                    <td class="Cell">
                        <a href="/StoreSeoNotification/Create/@Request.QueryString["storeMainPartyId"]?storeNotId=@itemMemberDesc.ID">
                            <img src="/Content/images/ac.png" />
                        </a>
                        @if (itemMemberDesc.IsFirst == true)
                            {
                        <a style="color: #339966;" href="/StoreSeoNotification/FirstProcess/@itemMemberDesc.ID?isFirst=0"><b>Öncelikli</b> Kaldır</a>
                        }
                            else
                            {
                        <a href="/StoreSeoNotification/FirstProcess/@itemMemberDesc.ID?isFirst=1">Öncelik Ver</a>
                        } 
                    </td>
                </tr>

                } 
                <tr></tr>
            </tbody>
        </table>
    </div>




@section HeadContent {

    <script type="text/javascript">

</script>

}

NeoSistem.Trinnk.Management/Views/StoreSeoNotification/AllSeoNotification.cshtml
@model FilterModel<NeoSistem.Trinnk.Management.Models.BaseMemberDescriptionModelItem>

@section TitleContent {

    Firma Seo Bildirimleri

}


    <div style="margin-top: 20px;">
        <h2 style="float: left;">Firma Seo Bildirimleri Tümü
        </h2>
    </div>
    <div style="width: 100%; margin: 0 auto;">
        @Html.Hidden("currentPage", Model.CurrentPage)
        <table cellpadding="5" cellspacing="0" class="TableList" style="width: 100%; margin-top: 5px">
            <thead>
                <tr>
                    <td class="Header" style="width: 10%">Firma Adı</td>
                    <td class="Header" style="width: 7%">Başlık</td>
                    <td class="Header" style="width: 45%">İçerik</td>
                    <td class="Header" style="width: 5%">İşlem Tarihi</td>
                    <td class="Header" style="width: 5%">Hatırlatma Tarihi</td>
                    <td class="Header" style="width: 5%">Atayan</td>
                    <td class="Header" style="width: 5%">Atanan</td>

                    <td class="Header HeaderEnd" style="width: 5%">Araçlar</td>
                </tr>
                <tr style="background-color: #F1F1F1">
                    <td class="CellBegin" align="center"></td>
                    <td class="Cell"></td>
                    <td class="CellBegin" align="center"></td>
                    <td class="Cell" style="width: 8%;">
                        <table border="0" cellspacing="0" cellpadding="0" style="width: 100%">
                            <tbody>
                                <tr>
                                    <td style="border: solid 1px #CCC; background-color: #FFF;">
                                        <input  id="createdDate" class="Search date" style="width: 75%; border: none;" />

                                        <span class="ui-icon ui-icon-close searchClear"
                                            onclick="clearSearch('date');" style="width: 7%;"></span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                    <td class="Cell"></td>
                    <td class="Cell"></td>
                    <td class="Cell"></td>
                    <td class="CellEnd"></td>
                </tr>
            </thead>
            <tbody id="table">
                @Html.Partial("_SeoNotificationList", Model)
            </tbody>
        </table>
    </div>




@section HeadContent {

    <script type="text/javascript">

        $(document).ready(function () {

            $('.date').datepicker({ "dateFormat": "dd.mm.yy" }).val();
            $('.Search').keyup(function (e) {
                if (e.keyCode == 13) {
                    SearchPost();
                }
            });

        });
        function PagePost(p) {
            $("#currentPage").val(p);
            SearchPost();
        }
        function SearchPost() {
            bilgimesajver();
            $.ajax({
                url: '/StoreSeoNotification/AllSeoNotification',
                data: {
                    page: $("#currentPage").val(),
                    createdDate: $("#createdDate").val()
                },
                type: 'post',
                success: function (data) {
                    $('#table').html(data);
                    allMessageClose();
                },
                error: function (x, a, r) {
                    allMessageClose();
                }
            });
        }

        function clearSearch(Id) {
            $('#' + Id).val('');
            $('#' + Id).trigger('keyup');
        }
    </script>

}

NeoSistem.Trinnk.Management/Views/StoreSeoNotification/Create.cshtml
@model NeoSistem.Trinnk.Management.Models.Stores.StoreSeoNotificationFormModel

@section TitleContent {

    Seo Bildirim Ekle

}
@section HeadContent {

    <script type="text/javascript" src="~/Content/Scripts/CKEditor/ckeditor.js"></script>
    <script type="text/javascript" src="~/Content/Scripts/CKFinder/ckfinder.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {

            $('#RemindDate').datepicker({ "dateFormat": "dd.mm.yy" }).val();
            CKEDITOR.replace('Text', {
                toolbar: [
                    '/',																					// Line break - next group will be placed in new line.
                    { name: 'basicstyles', items: ['Bold'] },
                ],

            });
                        CKEDITOR.replace('PreviousText', {
                toolbar: [
                    '/',																					// Line break - next group will be placed in new line.
                    { name: 'basicstyles', items: ['Bold'] },
                ],

            });

        });



    </script>
    <style type="text/css">
        .editor-label { padding-top: 5px; }
    </style>


}

    @using (Html.BeginForm("Create", "StoreSeoNotification", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        { 
    @Html.Partial("_StoreNotificationFormModel", Model) 
    } 

NeoSistem.Trinnk.Management/Views/StoreSeoNotification/Index.cshtml
@model NeoSistem.Trinnk.Management.Models.Stores.StoreSeoNotificationModel

@section TitleContent {

    Firma Seo Bildirimleri

}


    @if (Model.BaseMemberDescriptionModelItems.Where(x => x.LastDate != null).Count() == 0)
        {
            string newUrl = "/StoreSeoNotification/Create/"+Request.QueryString["storeMainPartyId"];
    
    <button type="button" style="width: 100px; float: right; height: 35px; margin-right: 300px; margin-top: 20px;" onclick="window.location='@newUrl'">
        Yeni Açıklama Girişi
    </button>
    
        } 

    <div style="margin-top: 20px;">
        <h2 style="float: left;">@Model.StoreName Seo Bildirimleri
        </h2>
    </div>
    <div style="width: 100%; margin: 0 auto;">
        <table cellpadding="5" cellspacing="0" class="TableList" style="width: 100%; margin-top: 5px">
            <thead>
                <tr>
                    <td class="Header">Başlık</td>
                    <td class="Header" style="width:35%;">İçerik</td>
                    <td class="Header" style="width:5%;">İşlem Tarihi</td>
                    <td class="Header" style="width:5%;">Hatırlatma Tarihi</td>
                    <td class="Header">Atayan</td>
                    <td class="Header">Atanan</td>
     
                    <td class="Header HeaderEnd">Araçlar</td>
                </tr>
            </thead>
            <tbody>
                @{int row = 0; }
                @foreach (var itemMemberDesc in Model.BaseMemberDescriptionModelItems.ToList())
                    {
                
                <tr id="@("row"+itemMemberDesc.ID)" class="@(row % 2 == 0 ? "Row" : "RowAlternate")">
                    <td class="Cell">@itemMemberDesc.Title</td>
                    <td class="Cell" style="font-size: 15px; width:35%;">@if (itemMemberDesc.Description != null)
                                                                  { 
                        @Html.Raw(itemMemberDesc.Description)
                         }
                        

                    </td>
                    <td class="Cell">@if (itemMemberDesc.InputDate != null)
                                         {
                                             string[] Inputdate = itemMemberDesc.InputDate.ToString().Split(' ');
                                                <span>@Inputdate[0] <font style='color:#C5D5DD'>@Inputdate[1] </font></span>
                                         }</td>
                    <td class="Cell">
                        @if (itemMemberDesc.LastDate.ToDateTime().Date >= DateTime.Now.Date)
                        {
                            string[] lastDate = itemMemberDesc.LastDate.ToString().Split(' ');
                            <span>@lastDate[0] <font style='color:#C5D5DD'>@lastDate[1] </font></span>
                        }
                        </td>
                    <td class="Cell" style="background-color: #2776e5; color: #fff">@itemMemberDesc.FromUserName</td>
                    <td class="Cell" style="background-color: #31c854; color: #fff">
                        @itemMemberDesc.ToUserName
                    </td>
                    <td class="Cell">
                        <a href="/StoreSeoNotification/Create/@Request.QueryString["storeMainPartyId"]?storeNotId=@itemMemberDesc.ID">
                            <img src="/Content/images/ac.png" />
                        </a>

                        <a style="cursor: pointer;" onclick="DeletePost(@itemMemberDesc.ID);">
                            <img src="/Content/images/delete.png" hspace="5" />
                        </a>

                    </td>
                </tr>

                } 
                <tr></tr>
            </tbody>
        </table>
    </div>




@section HeadContent {

    <script type="text/javascript">
        function DeletePost(descId) {
            if (confirm('Kaydı Silmek istediğinizden eminmisiniz ?')) {
                $.ajax({
                    url: '/StoreSeoNotification/Delete',
                    data: { id: descId },
                    type: 'post',
                    dataType: 'json',
                    success: function (data) {
                        if (data) {
                            $('#row' + descId).hide();
                        }
                  
                    }
                });
            }
        }
    </script>

}

NeoSistem.Trinnk.Management/Views/StoreSeoNotification/_SeoNotificationList.cshtml
@model FilterModel<NeoSistem.Trinnk.Management.Models.BaseMemberDescriptionModelItem>

@{int row = 0; }
@foreach (var itemMemberDesc in Model.Source.ToList())
    {

<tr id="@("row"+itemMemberDesc.ID)" class="@(row % 2 == 0 ? "Row" : "RowAlternate")">
    <td class="Cell"><a href="/Store/EditStore/@itemMemberDesc.StoreID">@itemMemberDesc.StoreName</a></td>
    <td class="Cell">@itemMemberDesc.Title</td>
    <td class="Cell" style="font-size: 15px;">@if (itemMemberDesc.Description != null)
                                                  { 
        @Html.Raw(itemMemberDesc.Description)
         }
        
    </td>
    <td class="Cell">@if (itemMemberDesc.InputDate != null)
                         {
                             string[] Inputdate = itemMemberDesc.InputDate.ToString().Split(' ');
                             @(Inputdate[0] + " ")
                            <font style='color:#C5D5DD'>@Inputdate[1]</font>
                         }
    </td>
    <td class="Cell">
        @if (itemMemberDesc.LastDate != null)
        {
            string[] lastDate = itemMemberDesc.LastDate.ToString().Split(' ');
            @(lastDate[0] + " ")
            <font style='color:#9d0825'>@lastDate[1]</font>
        }
    </td>
    <td class="Cell" style="background-color: #2776e5; color: #fff">@itemMemberDesc.FromUserName</td>
    <td class="Cell" style="background-color: #31c854; color: #fff">
        @itemMemberDesc.ToUserName
    </td>
    <td class="Cell">
        <a href="/StoreSeoNotification/Create/@Request.QueryString["storeMainPartyId"]?storeNotId=@itemMemberDesc.ID">
            <img src="/Content/images/ac.png" />
        </a>
        @if (Request.Url.ToString().ToLower().Contains("AllNotification")) { 
            } 


    </td>
</tr>

} 


<tr>
    <td class="ui-state ui-state-default" colspan="8" align="right" style="border-color: #DDD; border-top: none;">
        <div style="float: right;" class="pagination">
            <ul>
                @foreach (int page in Model.TotalLinkPages)
                {
                    <li>
                        @if (page == Model.CurrentPage)
                        {
                            <span class="currentpage">
                                @page
                            </span>
                        }
                        else
                        {
                            <a onclick="PagePost(@page)">
                                @page
                            </a>
                        }

                    </li>
                }
            </ul>
        </div>
    </td>
</tr>
<tr>
    <td class="ui-state ui-state-hover" colspan="17" align="right" style="border-color: #DDD; border-top: none;">
        Toplam Kayıt : <strong>
            @Model.TotalRecord</strong>
    </td>
</tr>

NeoSistem.Trinnk.Management/Views/StoreSeoNotification/_StoreNotificationFormModel.cshtml
@model NeoSistem.Trinnk.Management.Models.Stores.StoreSeoNotificationFormModel
   
@Html.HiddenFor(x=>x.StoreMainPartyId)
@Html.HiddenFor(x=>x.StoreSeoNotificationId)
<table>


    <tr>

    <td>
             <div class="editor-label">
                Başlık
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(x=>x.ConstantId, Model.Titles)
 
                <br />
                @Html.ValidationMessageFor(model => model.ConstantId)
            </div>
    </td>
        <td>
            <div class="editor-label">
                Hatırlatma Tarihi
            </div>
            <div class="editor-field">
                @Html.TextBox("RemindDate",DateTime.Now.Date.ToString("dd.MM.yyyy"),new {@autocomplete="off" })
                <br />
                @Html.ValidationMessageFor(model => model.RemindDate)
            </div>
        </td>

        <td>

            <div class="editor-field">
                Hatırlatma Saati
            </div>
            <div class="editor-field">
                <select name="time" style="width: 150px;">
                    <option value="">Seçiniz</option>
                    @for (int i = 6; i <= 23; i++)
                    {
                        for (int a = 0; a <= 3; a++)
                        {
                            if (a == 0)
                            {
                                <option value='@(i+":00")'>@(i + ":00")</option>
                            }
                            else if (a == 1)
                            {
                                <option value='@(i+":15")'>@(i + ":15")</option>
                            }
                            else if (a == 2)
                            {
                                <option value='@(i+":30")'>@(i + ":30")</option>
                            }
                            else
                            {
                                <option value='@(i+":45")'>@(i + ":45")</option>
                            }

                        }
                    }
                </select>
            </div>
        </td>

        <td>
            <div class="editor-label">
                Atama Yap
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(x=>x.ToUserId,Model.ToUsers)
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="4">
            <div class="editor-field">

                Açıklama:
        @Html.TextAreaFor(model => model.Text,new { @style = "width:100%; height:200px;"})
                <br />
                @Html.ValidationMessageFor(m=>m.Text)
            </div>
        </td>
    </tr>
    @if (Model.StoreSeoNotificationId != 0)
        {
    <tr>
        <td colspan="3">
            <div class="editor-field">
                @Html.HiddenFor(x=>x.StoreMainPartyId)
                Eski Açıklama:
        @Html.TextAreaFor(model => model.PreviousText,new { @style = "width:100%; height:200px;"})
                <br />

            </div>
        </td>
    </tr>
     } 
    <tr>
        <td colspan="3"></td>
        <td>
            @using (Html.BeginForm())
                { 
            <p>
                <button type="submit" style="width: 70px; height: 35px;">
                    Kaydet
                </button>

                <button type="button" style="width: 70px; height: 35px;" onclick="window.location='/Member/BrowseDesc/@ViewData["mid"]'">
                    İptal
                </button>
            </p>
             } 
            </div>
        </td>
    </tr>
</table>