NeoSistem.Trinnk.Management/Controllers/MessagesMTController.cs
namespace NeoSistem.Trinnk.Management.Controllers
{
    using EnterpriseEntity.Extensions.Data;
    using NeoSistem.Trinnk.Management.Models.Entities;
    using System.Linq;
    using System.Web.Mvc;

    public class MessagesMTController : BaseController
    {

        public ActionResult Index()
        {
            var entities = new TrinnkEntities();
            var model = entities.MessagesMTs.ToList();


            return View(model);
        }

        public ActionResult Create()
        {

            return View(new NeoSistem.Trinnk.Management.Models.Entities.MessagesMT());

        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(NeoSistem.Trinnk.Management.Models.Entities.MessagesMT model)
        {
            TrinnkEntities entities = new TrinnkEntities();
            var packet = new NeoSistem.Trinnk.Management.Models.Entities.MessagesMT
            {
                MessagesMTName = model.MessagesMTName,
                MessagesMTPropertie = model.MessagesMTPropertie,
                MessagesMTTitle = model.MessagesMTTitle,
                Mail = model.Mail,
                MailPassword = model.MailPassword,
                MailSendFromName = model.MailSendFromName
            };

            entities.MessagesMTs.AddObject(packet);
            entities.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult EditConstants(int id)
        {
            TrinnkEntities entities = new TrinnkEntities();
            var model = entities.MessagesMTs.Where(c => c.MessagesMTId == id).SingleOrDefault();
            return View(model);

        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult EditConstants(int id, NeoSistem.Trinnk.Management.Models.Entities.MessagesMT model)
        {
            TrinnkEntities entities = new TrinnkEntities();
            if (model.MessagesMTName == "templatemail")
            {
                MessagesMT newmodel = entities.MessagesMTs.Where(c => c.MessagesMTId == id).SingleOrDefault();
                newmodel.Mail = model.Mail;
                newmodel.MailPassword = model.MailPassword;
                newmodel.MailSendFromName = model.MailSendFromName;
                newmodel.MessagesMTPropertie = model.MessagesMTPropertie;
                newmodel.MessagesMTTitle = model.MessagesMTTitle;
                newmodel.MailContent = model.MailContent;
                entities.SaveChanges();
                var otherMail = entities.MessagesMTs.Where(x => x.MailContent != null && x.MessagesMTName != "templatemail");

                foreach (var item in otherMail)
                {
                    using (var entities1 = new TrinnkEntities())
                    {
                        var memberMessage = entities1.MessagesMTs.FirstOrDefault(x => x.MessagesMTId == item.MessagesMTId);
                        memberMessage.MessagesMTPropertie = model.MessagesMTPropertie.Replace("#icerik#", item.MailContent);
                        entities1.SaveChanges();
                    }
                }
                var mailConsant = entities.Constants.Where(x => x.ConstantType == 14 || x.ConstantType == 15);
                foreach (var item in mailConsant.ToList())
                {
                    using (var entities1 = new TrinnkEntities())
                    {
                        var constant = entities1.Constants.FirstOrDefault(x => x.ConstantId == item.ConstantId);

                        constant.ContstantPropertie = model.MessagesMTPropertie.Replace("#icerik#", constant.ConstantMailContent);
                        entities1.SaveChanges();
                    }

                }
            }
            else
            {
                MessagesMT newmodel = entities.MessagesMTs.Where(c => c.MessagesMTId == id).SingleOrDefault();
                newmodel.Mail = model.Mail;
                newmodel.MailPassword = model.MailPassword;
                newmodel.MailSendFromName = model.MailSendFromName;
                var messageTemplate = entities.MessagesMTs.FirstOrDefault(c => c.MessagesMTName == "templatemail");
                var content = messageTemplate.MessagesMTPropertie;
                content = content.Replace("#icerik#", model.MailContent);
                newmodel.MessagesMTPropertie = content;
                newmodel.MessagesMTTitle = model.MessagesMTTitle;
                newmodel.MailContent = model.MailContent;
                entities.SaveChanges();

            }
            return RedirectToAction("Index");

        }

        public string Delete(int id)
        {
            TrinnkEntities entities = new TrinnkEntities();
            var messages = entities.MessagesMTs.First(x => x.MessagesMTId == id);
            entities.MessagesMTs.DeleteObject(messages);
            entities.SaveChanges();
            return "silindi";
        }

    }
}

NeoSistem.Trinnk.Management/Views/MessagesMT/Create.cshtml
@model NeoSistem.Trinnk.Management.Models.Entities.MessagesMT

@section TitleContent {

	Create

}
@section HeadContent {

<script src="http: //code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="~/Content/Scripts/CKEditor/ckeditor.js"></script>
  <script type="text/javascript" src="~/Content/Scripts/CKFinder/ckfinder.js"></script>

}


  <script type="text/javascript">
    $(document).ready(function () {
      $('td').attr('valign', 'top');

      $('#MessagesMTPropertie').focus(function () {
        $('#activeText').val('#MessagesMTPropertie')
      });

      $('#MessagesMTTitle').focus(function () {
        $('#activeText').val('#MessagesMTTitle')
      });

      $('#MessagesMTName').focus(function () {
        $('#activeText').val('#MessagesMTName')
      });


      $('button').click(function () {
        if ($('#activeText').val() == '') {
          alert('Parametre göndermek için göndermek istediğiniz alanı seçmelisiniz.')
        }
        else {
          $($('#activeText').val()).val($($('#activeText').val()).val() + ' ' + $(this).val());
        }
      });

    });
 
   
  </script>
  <input id="activeText" type="hidden" value="" />
   @using (Html.BeginForm("Create", "MessagesMT", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary(true)
        
        <fieldset>
            <legend>Güncelle</legend>
            <div class="editor-label" style="margin:20px;">
            <span style="color:#868686; font-family:Arial; font-size:14px;">
              Başlık 
              <br />
              </span>
            </div>
            <div class="editor-field" style="margin-left:20px;">
                @Html.TextBoxFor(model => model.MessagesMTName, new { style = "width: 300px;border: solid 1px #bababa;" })
                @Html.ValidationMessageFor(model => model.MessagesMTName)
            </div>
            <div class="editor-label" style="margin-left:20px; margin-top:15px;color:#868686; font-family:Arial; font-size:14px;">
                Mail Konusu
            </div>
            <div class="editor-field" style="margin-left:20px;">
                 @Html.TextBoxFor(model => model.MessagesMTTitle, new { style = "width: 300px;border: solid 1px #bababa;" })
            </div>
                        <div class="editor-label" style="margin-left:20px; margin-top:15px;color:#868686; font-family:Arial; font-size:14px;">
                Mail Adresi
            </div>
            
            <div class="editor-field" style="margin-left:20px;">
                 @Html.TextBoxFor(model => model.Mail, new { style = "width: 300px;border: solid 1px #bababa;" })
            </div>
                <div class="editor-label" style="margin-left:20px; margin-top:15px;color:#868686; font-family:Arial; font-size:14px;">
                Mail Şifresi
            </div>
            
            <div class="editor-field" style="margin-left:20px;">
                 @Html.TextBoxFor(model => model.MailPassword, new { style = "width: 300px;border: solid 1px #bababa;" })
            </div>

                          <div class="editor-label" style="margin-left:20px; margin-top:15px;color:#868686; font-family:Arial; font-size:14px;">
                Mail Gözüken Ad
            </div>
            
            <div class="editor-field" style="margin-left:20px;">
                 @Html.TextBoxFor(model => model.MailSendFromName, new { style = "width: 300px;border: solid 1px #bababa;" })
            </div>   
            <div class="editor-label" style="margin-left:20px; margin-top:15px;color:#868686; font-family:Arial; font-size:14px;">
                Açıklama
            </div>
            <div class="editor-field" style="margin-left:5px; margin-top:15px;">
                @Html.TextAreaFor(model => model.MessagesMTPropertie)
                @Html.ValidationMessageFor(model => model.MessagesMTPropertie)
            </div>
            <div style="border-style:solid; border-color:Black; margin:10px; border-width:1px;">
            Üye mail:
            <button type="button" title="Aktivasyon kodu" value="#activationcode#">
            Aktivasyon kodu</button>
          <button type="button" title=" Üye Ad Soyadı" value="#uyeadisoyadi#">
            Üye Ad Soyadı</button>
          <button type="button" title="Kullanıcı adı" value="#kullaniciadi#">
            Kullanıcı adı</button>
          <button type="button" title="Üyelik tipi" value="#uyeliktipi#">
            Üyelik tipi</button>
          <button type="button" title="Paket Tipi" value="#pakettipi#">
            Paket Tipi</button>
          <button type="button" title="Şifre" value="#sifre#">
            Şifre</button>
      <br />
            Firma maili: 
             <button type="button" title="İlan Tekil Tıklama" value="#tekililantiklama#">
            İlan Tekil Tıklama</button>
          <button type="button" title="Çoğul İlan Tıklama" value="#cogulilantiklama#">
            Çoğul İlan Tıklama</button>
          <button type="button" title="İlan Tıklama Oranı" value="#ilantiklamaorani#">
            İlan Tıklama Oranı</button>
          <button type="button" title="Firma Çoğul Tıklama" value="#firmacogultiklama#">
            Firma Çoğul Tıklama</button>
          <button type="button" title="İlan Sayısı" value="#ilansayisi#">
            İlan Sayısı</button>
          <button type="button" title="Firma Ürünler Köprü" value="#firmaurunlerkopru#">
            Firma Ürünler Köprü</button>
          <button type="button" title="Firma İstatistik köprü" value="#firmaistatistikkopru#">
            Firma İstatistik köprü</button>
          <button type="button" title="Firma Düzenle" value="#firmaduzenle#">
            Firma Düzenle</button>
          <button type="button" title="İlan İstatistik köprü" value="#ilanistatistikkopru#">
            İlan İstatistik köprü</button>
          <button type="button" title="Kullanıcı adı" value="#kullaniciadi#">
            Kullanıcı adı</button>
          <button type="button" title="Şifre" value="#sifre#">
            Şifre</button>
          <button type="button" title="Üyelik paket" value="#uyelikpaket#">
            Üyelik paket</button>
          <button type="button" title="Üye Adı Soyadı" value="#uyeadisoyadi#">
            Üye Adı Soyadı</button>
          <button type="button" title="bunu ekleyince buradan diye link koyar vede bu link firmanın düzenleme sayfasına gitmeyi sağlar" value="#firmaduzenlemekopru#">
            Firma Düzenleme Köprü</button>
          <button type="button" title="Firma Köprü" value="#firmakopru#">
            Firma Köprü</button>
          <button type="button" title="Firma Adı" value="#firmaadi#">
            Firma Adı</button>
            <button type="button" title="firma üyelik yükseltme" value="#firmauyelikyukseltme#">
            firma üyelik yükseltme</button>
            <br />
          İlan maili:
          <br />
          <button type="button" title="Bireyselden Firma Üyeliğine Köprü" value="#bireyseldenfirmauyeligikopru#">
            Bireyselden Firma Üyeliğine Köprü</button>
          <button type="button" title="İlan no" value="#ilanno#">
            İlan no</button>
          <button type="button" title="İlan Adı" value="#ilanadi#">
            İlan Adı</button>
          <button type="button" title="Ürün Adı" value="#urunadi#">
            Ürün Adı</button>
          <button type="button" title="İlan Düzenleme köprü" value="#ilanduzenlemekopru#">
            İlan Düzenleme köprü</button>
          <button type="button" title="İlan giriş" value="#ilangiris#">
            İlan giriş</button>
          <button type="button" title="Üye Adı Soyadı" value="#uyeadisoyadi#">
            Üye Adı Soyadı</button>
          <button type="button" title="İlan Adı Köprü" value="#ilanadikopru#">
            İlan Adı Köprü</button>            
            </div>
            <p>
                <input type="submit" value="Güncelle" />
            </p>
        </fieldset>

     } 
         <script type="text/javascript" defer="defer">
             var editor = CKEDITOR.replace('MessagesMTPropertie', { toolbar: 'webtool',allowedContent :true });
           CKFinder.SetupCKEditor(editor, '/Scripts/CKFinder/');
  </script>

NeoSistem.Trinnk.Management/Views/MessagesMT/EditConstants.cshtml
@model NeoSistem.Trinnk.Management.Models.Entities.MessagesMT

@section TitleContent {

	EditConstants

}
@section HeadContent {

  <script type="text/javascript" src="~/Content/Scripts/CKEditor/ckeditor.js"></script>
  <script type="text/javascript" src="~/Content/Scripts/CKFinder/ckfinder.js"></script>

}


  <script type="text/javascript">
    $(document).ready(function () {
      $('td').attr('valign', 'top');

      $('.cke_show_borders').focus(function () {
        $('#activeText').val('.cke_show_borders')
      });
      $('#MessagesMTPropertie').focus(function () {
        $('#activeText').val('#MessagesMTPropertie')
      });

      $('#MessagesMTTitle').focus(function () {
        $('#activeText').val('#MessagesMTTitle')
      });

      $('#MessagesMTName').focus(function () {
        $('#activeText').val('#MessagesMTName')
      });


      $('button').click(function () {
        if ($('#activeText').val() == '') {
          alert('Parametre göndermek için göndermek istediğiniz alanı seçmelisiniz.')
        }
        else {
          $($('#activeText').val()).val($($('#activeText').val()).val() + ' ' + $(this).val());
        }
      });

    });
 
   
  </script>
     @using (Html.BeginForm()) {
        @Html.ValidationSummary(true)
        <input id="activeText" type="hidden" value="" />
        <fieldset>
            <legend>Güncelle</legend>
            <div class="editor-label" style="margin:20px;">
            <span style="color:#868686; font-family:Arial; font-size:14px;">
              Başlık 
              <br />
              </span>
            </div>
            <div class="editor-field" style="margin-left:20px;">
                @Html.TextBoxFor(model => model.MessagesMTName, new { style = "width: 300px;border: solid 1px #bababa;"})
                @Html.ValidationMessageFor(model => model.MessagesMTName)
            </div>
            <div class="editor-label" style="margin-left:20px; margin-top:15px;color:#868686; font-family:Arial; font-size:14px;">
                Mail Konusu
            </div>
                <div class="editor-field" style="margin-left:20px;">
                 @Html.TextBoxFor(model => model.MessagesMTTitle, new { style = "width: 300px;border: solid 1px #bababa;" })
            </div>
            <div class="editor-label" style="margin-left:20px; margin-top:15px;color:#868686; font-family:Arial; font-size:14px;">
                Mail Adresi
            </div>
            
            <div class="editor-field" style="margin-left:20px;">
                 @Html.TextBoxFor(model => model.Mail, new { style = "width: 300px;border: solid 1px #bababa;" })
            </div>
                <div class="editor-label" style="margin-left:20px; margin-top:15px;color:#868686; font-family:Arial; font-size:14px;">
                Mail Şifresi
            </div>
            
            <div class="editor-field" style="margin-left:20px;">
                 @Html.TextBoxFor(model => model.MailPassword, new { style = "width: 300px;border: solid 1px #bababa;" })
            </div>

                          <div class="editor-label" style="margin-left:20px; margin-top:15px;color:#868686; font-family:Arial; font-size:14px;">
                Mail Gözüken Ad
            </div>
            
            <div class="editor-field" style="margin-left:20px;">
                 @Html.TextBoxFor(model => model.MailSendFromName, new { style = "width: 300px;border: solid 1px #bababa;" })
            </div>           
        
            <div class="editor-label" style="margin-left:20px; margin-top:15px;color:#868686; font-family:Arial; font-size:14px;">
                Açıklama
            </div>
            <div class="editor-field" style="margin-left:5px; margin-top:15px;">
                @if (Model.MessagesMTName == "templatemail")
                  { 
                       @Html.TextAreaFor(model => model.MessagesMTPropertie)
                @Html.ValidationMessageFor(model => model.MessagesMTPropertie)
                } else{
                @Html.TextAreaFor(model => model.MailContent)
                @Html.ValidationMessageFor(model => model.MailContent)
                } 
            </div>
            <div style="border-style:solid; border-color:Black; margin:10px; border-width:1px;">
            Üye mail:
            <button type="button" title="Aktivasyon kodu" value="#activationcode#">
            Aktivasyon kodu</button>
          <button type="button" title=" Üye Ad Soyadı" value="#uyeadisoyadi#">
            Üye Ad Soyadı</button>
          <button type="button" title="Kullanıcı adı" value="#kullaniciadi#">
            Kullanıcı adı</button>
          <button type="button" title="Üyelik tipi" value="#uyeliktipi#">
            Üyelik tipi</button>
          <button type="button" title="Paket Tipi" value="#pakettipi#">
            Paket Tipi</button>
          <button type="button" title="Şifre" value="#sifre#">
            Şifre</button>
      <br />
            Firma maili: 
             <button type="button" title="İlan Tekil Tıklama" value="#tekililantiklama#">
            İlan Tekil Tıklama</button>
          <button type="button" title="Çoğul İlan Tıklama" value="#cogulilantiklama#">
            Çoğul İlan Tıklama</button>
          <button type="button" title="İlan Tıklama Oranı" value="#ilantiklamaorani#">
            İlan Tıklama Oranı</button>
          <button type="button" title="Firma Çoğul Tıklama" value="#firmacogultiklama#">
            Firma Çoğul Tıklama</button>
          <button type="button" title="İlan Sayısı" value="#ilansayisi#">
            İlan Sayısı</button>
          <button type="button" title="Firma Ürünler Köprü" value="#firmaurunlerkopru#">
            Firma Ürünler Köprü</button>
          <button type="button" title="Firma İstatistik köprü" value="#firmaistatistikkopru#">
            Firma İstatistik köprü</button>
          <button type="button" title="Firma Düzenle" value="#firmaduzenle#">
            Firma Düzenle</button>
          <button type="button" title="İlan İstatistik köprü" value="#ilanistatistikkopru#">
            İlan İstatistik köprü</button>
          <button type="button" title="Kullanıcı adı" value="#kullaniciadi#">
            Kullanıcı adı</button>
          <button type="button" title="Şifre" value="#sifre#">
            Şifre</button>
          <button type="button" title="Üyelik paket" value="#uyelikpaket#">
            Üyelik paket</button>
          <button type="button" title="Üye Adı Soyadı" value="#uyeadisoyadi#">
            Üye Adı Soyadı</button>
          <button type="button" title="bunu ekleyince buradan diye link koyar vede bu link firmanın düzenleme sayfasına gitmeyi sağlar" value="#firmaduzenlemekopru#">
            Firma Düzenleme Köprü</button>
          <button type="button" title="Firma Köprü" value="#firmakopru#">
            Firma Köprü</button>
          <button type="button" title="Firma Adı" value="#firmaadi#">
            Firma Adı</button>
            <button type="button" title="firma üyelik yükseltme" value="#firmauyelikyukseltme#">
            firma üyelik yükseltme</button>
                <button type="button" title="Mail İmza" value="#signature#">
            Mail İmza</button>    
            <br />
          İlan maili:
          <br />
          <button type="button" title="Bireyselden Firma Üyeliğine Köprü" value="#bireyseldenfirmauyeligikopru#">
            Bireyselden Firma Üyeliğine Köprü</button>
          <button type="button" title="İlan no" value="#ilanno#">
            İlan no</button>
          <button type="button" title="İlan Adı" value="#ilanadi#">
            İlan Adı</button>
          <button type="button" title="Ürün Adı" value="#urunadi#">
            Ürün Adı</button>
          <button type="button" title="İlan Düzenleme köprü" value="#ilanduzenlemekopru#">
            İlan Düzenleme köprü</button>
          <button type="button" title="İlan giriş" value="#ilangiris#">
            İlan giriş</button>
          <button type="button" title="Üye Adı Soyadı" value="#uyeadisoyadi#">
            Üye Adı Soyadı</button>
          <button type="button" title="İlan Adı Köprü" value="#ilanadikopru#">
            İlan Adı Köprü</button>
                        
            </div>
            <p>
                <input type="submit" value="Güncelle" />
            </p>
        </fieldset>

     } 
<script type="text/javascript" defer="defer">
      @if (Model.MessagesMTName == "templatemail")
      {
          @:var editor = CKEDITOR.replace('MessagesMTPropertie', { toolbar: 'webtool', allowedContent: true });
          @:CKFinder.SetupCKEditor(editor, '/Scripts/CKFinder/');
      }
      else
      {
          @:var editor = CKEDITOR.replace('MailContent', { toolbar: 'webtool', allowedContent: true });
          @:CKFinder.SetupCKEditor(editor, '/Scripts/CKFinder/');
      }
</script>

NeoSistem.Trinnk.Management/Views/MessagesMT/Index.cshtml
@model ICollection<NeoSistem.Trinnk.Management.Models.Entities.MessagesMT>

@section TitleContent {

	Index

}
@section HeadContent {

<link rel="stylesheet" href="~/content/Scripts/SuperBox/jquery.superbox.css" type="text/css" media="all" />
  <script type="text/javascript" src="~/Content/Scripts/SuperBox/jquery.superbox.js"></script>
  	<style type="text/css">
		/* Custom Theme */
		#superbox-overlay{background:#e0e4cc;}
		#superbox-container .loading{width:32px;height:32px;margin:0 auto;text-indent:-9999px;background:url(styles/loader.gif) no-repeat 0 0;}
		#superbox .close a{float:right;padding:0 5px;line-height:20px;background:#333;cursor:pointer;}
		#superbox .close a span{color:#fff;}
		#superbox .nextprev a{float:left;margin-right:5px;padding:0 5px;line-height:20px;background:#333;cursor:pointer;color:#fff;}
		#superbox .nextprev .disabled{background:#ccc;cursor:default;}
	</style>


}


  <div style="width: 100%; margin: 0 auto;">
    <table cellpadding="5" cellspacing="0" class="TableList" style="width: 100%; margin-top: 5px">
      <thead>
        <tr>
          <td class="Header HeaderBegin" unselectable="on">
            Mesaj Adı
          </td>
          <td id="tabloadd" class="Header" style="width: 70px; height: 19px;">
          </td>
          <td class="Header" style="width: 70px; height: 19px">
          <a style="padding-bottom: 5px; cursor: pointer; float:left; margin-right:7px;" href="/MessagesMt/Create">ekle</a>
          </td>
        </tr>
      </thead>
      <tbody id="table">
       @{ int row = 0; }
@foreach (var item in Model)
{
    row++;
<tr id="@("row"+item.MessagesMTId)" class="@(row % 2 == 0 ? "Row" : "RowAlternate")">
  <td class="CellBegin">
    @item.MessagesMTName
  </td>
    <td class="Cell">
  <a style="padding-bottom: 5px; cursor: pointer; float:left; margin-right:7px;" href="/MessagesMt/EditConstants/@item.MessagesMTId">içerik</a>
  </td>
  <td class="CellEnd" style="width:100px;">
    <a style="padding-bottom: 5px; cursor: pointer" onclick="EditConstant(@item.MessagesMTId);">
      <div style="float: left; margin-right: 10px">
        <img src="/Content/images/edit.png" />
      </div>
    </a>@*<a style="cursor: pointer;" href="MessagesMT/Delete?id=<%:item.MessagesMTId %>">
      <div style="float: left;">
        <img src="/Content/images/delete.png" />
      </div>
    </a>*@
  </td>
</tr>
 } 
<tr>
  <td class="ui-state ui-state-default" colspan="7" align="right" style="border-color: #DDD;
    border-top: none; border-bottom: none;">
    <div style="float: right;" class="pagination">
      <ul>
      </ul>
    </div>
  </td>
</tr>

      </tbody>
@*      <tfoot>
        <tr>
          <td class="ui-state ui-state-hover" style="border-color: #DDD;
            border-top: none; padding-right: 10px" colspan="1" valign="top" style="width: 150px;">
          <%:Ajax.ActionLink("Hesapla", "ProductRateCalculate", new AjaxOptions() { UpdateTargetId = "statisticproduct", HttpMethod = "Post" })%>
          </td>
          <td class="ui-state ui-state-hover" style="border-color: #DDD;
            border-top: none; padding-right: 10px" colspan="1">
           : <div id="statisticproduct" style="margin-top: 5px">

            </div>
          </td>
          <td class="ui-state ui-state-hover" colspan="1" align="right" style="border-color: #DDD;
            border-top: none; padding-right: 10px">
            Toplam Kayıt : <strong>
              <%= Model.Count %></strong>
          </td>
        </tr>
      </tfoot>*@
    </table>
  </div>