NeoSistem.Trinnk.Management/Models/ViewModel/CreditCardViewModel.cs
namespace NeoSistem.Trinnk.Management.Models
{
    using NeoSistem.Trinnk.Management.Models.Entities;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    public class CreditCardViewModel
    {
        public CreditCard CreditCard { get; set; }
        public IList<CreditCardInstallment> CreditCardInstallmentItems { get; set; }

        public SelectList VirtualPosItems
        {
            get
            {
                IList<VirtualPos> VirtualPosItems = null;
                using (var entities = new TrinnkEntities())
                {
                    VirtualPosItems = entities.VirtualPos.ToList();
                }
                VirtualPosItems.Insert(0, new VirtualPos { VirtualPosId = 0, VirtualPostName = "< Lütfen Seçiniz >" });
                return new SelectList(VirtualPosItems, "VirtualPosId", "VirtualPostName", 0);
            }
        }


    }
}

NeoSistem.Trinnk.Management/Controllers/CreditCardController.cs
namespace NeoSistem.Trinnk.Management.Controllers
{
    using EnterpriseEntity.Extensions;
    using EnterpriseEntity.Extensions.Data;
    using Models;
    using MvcContrib.Pagination;
    using NeoSistem.Trinnk.Management.Models.Entities;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    public class CreditCardController : BaseController
    {
        internal static readonly string SESSION_USERID = "CreditCardInstallment";

        public IList<CreditCardInstallment> SessionCreditCardInstallmentItems
        {
            get
            {
                if (Session[SESSION_USERID] == null)
                {
                    Session[SESSION_USERID] = new List<CreditCardInstallment>();
                }
                return Session[SESSION_USERID] as List<CreditCardInstallment>;
            }
            set { Session[SESSION_USERID] = value; }
        }

        public ActionResult Index()
        {
            PAGEID = PermissionPage.KrediKartiListesi;

            var pftypeItems = entities.CreditCards.ToList();
            return View(pftypeItems);
        }

        public ActionResult Create()
        {
            PAGEID = PermissionPage.YeniKrediKartiTanimi;

            SessionCreditCardInstallmentItems = null;
            return View(new CreditCardViewModel { CreditCardInstallmentItems = SessionCreditCardInstallmentItems });
        }

        [HttpPost]
        public ActionResult Create(CreditCardViewModel model)
        {
            try
            {
                var curCreditCard = new CreditCard
                {
                    CreditCardName = model.CreditCard.CreditCardName,
                    VirtualPosId = model.CreditCard.VirtualPosId,
                    Active = model.CreditCard.Active
                };
                entities.CreditCards.AddObject(curCreditCard);
                entities.SaveChanges();

                foreach (var item in SessionCreditCardInstallmentItems.OrderBy(c => c.CreditCardInstallmentId))
                {
                    var curCreditCardInstallment = new CreditCardInstallment
                    {
                        CreditCardValue = item.CreditCardValue,
                        CreditCardId = curCreditCard.CreditCardId,
                        CreditCardCount = item.CreditCardCount
                    };
                    entities.CreditCardInstallments.AddObject(curCreditCardInstallment);
                }
                entities.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult Delete(byte id)
        {
            try
            {
                var curCreditCard = entities.CreditCards.SingleOrDefault(c => c.CreditCardId == id);
                entities.CreditCards.DeleteObject(curCreditCard);
                entities.SaveChanges();
            }
            catch (Exception)
            {
                return Json(false);
                throw;
            }
            return Json(true);
        }

        public ActionResult Edit(int id)
        {
            PAGEID = PermissionPage.KrediKartiDuzenle;

            SessionCreditCardInstallmentItems.Clear();

            var model = new CreditCardViewModel();
            var curCreditCard = entities.CreditCards.SingleOrDefault(c => c.CreditCardId == id);

            if (curCreditCard != null)
            {
                model.CreditCard = curCreditCard;
                model.CreditCardInstallmentItems = entities.CreditCardInstallments.Where(c => c.CreditCardId == id).ToList();
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(byte id, CreditCardViewModel model, string[] VirtualPostInstallment)
        {
            try
            {
                var curCreditCard = entities.CreditCards.SingleOrDefault(c => c.CreditCardId == id);
                curCreditCard.CreditCardName = model.CreditCard.CreditCardName;
                curCreditCard.VirtualPosId = model.CreditCard.VirtualPosId;
                curCreditCard.Active = model.CreditCard.Active;

                entities.SaveChanges();

                if (VirtualPostInstallment != null)
                {
                    for (int i = 0; i < VirtualPostInstallment.Length; i++)
                    {
                        var tempVpi = VirtualPostInstallment.GetValue(i);
                        var tempVpiId = tempVpi.ToString().Split('&').GetValue(0).ToByte();
                        var tempVpiValue = tempVpi.ToString().Split('&').GetValue(1).ToDecimal();

                        var vpi = entities.CreditCardInstallments.SingleOrDefault(c => c.CreditCardInstallmentId == tempVpiId);

                        if (tempVpi.ToString().Split('&').Length == 3)
                        {
                            vpi.CreditCardCount = tempVpi.ToString().Split('&').GetValue(2).ToByte();
                        }
                        else
                        {
                            vpi.CreditCardCount = tempVpi.ToString().Split('&').GetValue(2).ToByte();
                        }

                        vpi.CreditCardValue = tempVpiValue;
                    }
                }
                entities.SaveChanges();


                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult SetVirtualPostInstallment(string value, byte count, byte? vpId)
        {
            if (!vpId.HasValue)
            {
                byte id = (SessionCreditCardInstallmentItems.Count + 1).ToByte();
                SessionCreditCardInstallmentItems.Add(new CreditCardInstallment { CreditCardValue = value.ToDecimal(), CreditCardInstallmentId = id, CreditCardCount = count });
                return View("CreditCardInstallment", SessionCreditCardInstallmentItems);
            }
            else
            {
                var vpi = new CreditCardInstallment { CreditCardValue = value.ToDecimal(), CreditCardId = vpId, CreditCardCount = count };
                entities.CreditCardInstallments.AddObject(vpi);
                entities.SaveChanges();

                var vpiItems = entities.CreditCardInstallments.Where(c => c.CreditCardId == vpId).ToList();
                return View("CreditCardInstallmentForEdit", vpiItems);
            }
        }

        public ActionResult DeleteVirtualPostInstallment(byte value, byte? vpId)
        {
            if (!vpId.HasValue)
            {
                SessionCreditCardInstallmentItems.RemoveAt(value - 1);
                return View("CreditCardInstallment", SessionCreditCardInstallmentItems);
            }
            else
            {
                var vpi = entities.CreditCardInstallments.SingleOrDefault(c => c.CreditCardInstallmentId == value);
                entities.DeleteObject(vpi);
                entities.SaveChanges();

                var vpiItems = entities.CreditCardInstallments.Where(c => c.CreditCardId == vpId.Value).ToList();
                return View("CreditCardInstallment", vpiItems);
            }
        }

        public ActionResult CreditCardLog(int? page)
        {
            PAGEID = PermissionPage.KrediKartıLog;
            var cclog = (from c in entities.CreditCardLogs

                         select c).ToList().OrderByDescending(c => c.Date).AsPagination(page ?? 1, 25);

            ViewData["Sayfa"] = cclog.TotalPages;
            ViewData["Curr"] = cclog.PageNumber;
            ViewData["Tot"] = cclog.TotalItems;

            return View(cclog);

        }
    }
}

NeoSistem.Trinnk.Management/Views/CreditCard/Create.cshtml
@model CreditCardViewModel

@section TitleContent {


}
@section HeadContent {

  <script type="text/javascript">
    function SetVirtualPostInstallment(value, count) {
      $.ajax({
        url: '/CreditCard/SetVirtualPostInstallment',
        data: { value: value, count: count },
        cache: false,
        success: function (data) { $('#divVirtualPostInstallment').html(data) },
        error: function (x) { alert(x.responseText) }
      });
    }

    function deleteInstallment(value) {
      if (confirm("Taksit işlemini silmek istediğinizden eminmisiniz ?")) {
        $.ajax({
          url: '/CreditCard/DeleteVirtualPostInstallment',
          data: { value: value },
          cache: false,
          success: function (data) { $('#divVirtualPostInstallment').html(data) },
          error: function (x) { alert(x.responseText) }
        });
      }
    }
    
  </script>

}

  @using (Html.BeginForm("Create", "CreditCard", FormMethod.Post))
    {
  <div style="float: left; width: 64%; padding-top: 10px; padding-left: 10px;">
    <button type="submit" style="width: 70px; height: 35px;">
      Kaydet
    </button>
    <button type="button" style="width: 70px; height: 35px;" onclick="window.location='/CreditCard/Index'">
      İptal
    </button>
    <br />
    <div style="border-bottom: dashed 1px #c0c0c0; width: 100%; height: 1px; margin-top: 15px;
      margin-bottom: 10px;">
    </div>
  </div>
  <div style="float: left;">
    <div style="float: left;">
      <table class="tableForm" style="padding-top: 10px; height: auto;">
        <tr>
          <td style="width: 120px;">
            Kredi Kartı Tanımı :
          </td>
          <td>
          
            @Html.TextBoxFor(model => model.CreditCard.CreditCardName, new { style = "width:300px" })
          </td>
        </tr>
               <tr>
          <td>
              Durum:
          </td>
          <td>@Html.CheckBox("Active")</td>
              </tr>
        <tr>
          <td style="width: 120px;">
            Sanal Pos :
          </td>
          <td>
            @Html.DropDownListFor(c => c.CreditCard.VirtualPosId, Model.VirtualPosItems)
          </td>
        </tr>
      </table>
    </div>
    <div style="float: left;">
      <div style="float: left; margin-top: 13px; float: left; width: 500px; margin-left: 20px;
        border-left: dashed 1px #bababa; padding-left: 20px; min-height: 70px;">
        <div style="float: left; width: 100%; padding-bottom: 10px; border-bottom: dashed 1px #bababa">
          Taksit ve Vade Farkları
        </div>
        <div style="float: left; margin-top: 10px; width: 100%;">
          <div style="float: left;">
            Taksit Sayısı:
            <input type="text" style="width: 40px;" id="txtInstallmentCount" />
          </div>
          <div style="float: left; margin-left: 5px;">
            Vade:
            <input type="text" style="width: 70px;" id="txtInstallment" />
            <button type="button" onclick="SetVirtualPostInstallment($('#txtInstallment').val(), $('#txtInstallmentCount').val());">
              Taksit Ekle
            </button>
          </div>
        </div>
        <div style="float: left; width: 349px;" id="divVirtualPostInstallment">
          @Html.Partial("CreditCardInstallment", Model.CreditCardInstallmentItems)
        </div>
      </div>
    </div>
  </div>
  <div style="float: left; width: 100%; padding-left: 10px;">
    <div style="border-bottom: dashed 1px #c0c0c0; width: 100%; height: 1px; margin-top: 15px;
      margin-bottom: 10px;">
    </div>
    <br />
    <button type="submit" style="width: 70px; height: 35px;">
      Kaydet
    </button>
    <button type="button" style="width: 70px; height: 35px;" onclick="window.location='/CreditCard/Index'">
      İptal
    </button>
  </div>
  } 

NeoSistem.Trinnk.Management/Views/CreditCard/CreditCardInstallment.cshtml
@model IList<CreditCardInstallment>
<div style="float: left; border: solid 1px #bababa; border-bottom: none; border-right: none;
  margin-top: 15px;">
  @foreach (var item in Model)
     { 
  <div style="float: left; width: 168px; height: 21px; background-color: #ececee; padding-top: 3px;
    padding-left: 5px; border-bottom: solid 1px #bababa; border-right: solid 1px #bababa">
    <div style="float: left; width: 45px;">
      T- <input type=text value="@item.CreditCardCount" disabled=disabled style="width:25px;padding-top:0px;height:15px;" />
    </div>
    <div style="float: left; margin-left: 10px; width: 95px; padding: 0px;">
      <div style="float: left;">
        %</div>
      <div style="float: left;">
        <input type="text" value="@item.CreditCardValue" style="width: 30px;
          float: left; padding: 0px; margin-left: 3px; text-align: center;" disabled=disabled /></div>
      <div style="float: right; margin-left: 6px;">
        <a style="cursor: pointer;" title="Sil" onclick="deleteInstallment(@item.CreditCardInstallmentId);">
          <img src="/Content/Images/vcard_delete.png" /></a></div>
    </div>
  </div>
   } 
</div>

NeoSistem.Trinnk.Management/Views/CreditCard/CreditCardInstallmentForEdit.cshtml
@model IList<CreditCardInstallment>
<div style="float: left; border: solid 1px #bababa; border-bottom: none; border-right: none;
  margin-top: 15px;">
  @foreach (var item in Model)
  { 
  <div style="float: left; width: 168px; height: 21px; background-color: #ececee; padding-top: 3px;
    padding-left: 5px; border-bottom: solid 1px #bababa; border-right: solid 1px #bababa">
    <div style="float: left; width: 45px;">
      T-<input type="text" id="input@item.CreditCardInstallmentIdCount" value="@item.CreditCardCount" style="width: 25px;
        padding-top: 0px; height: 15px; margin-left: 2px;"
         onkeyup="setVPIKeyupData('hdn@item.CreditCardInstallmentId','@item.CreditCardInstallmentId', $('#input@item.CreditCardInstallmentIdValue').val(), $(this).val());"/>
    </div>
    <div style="float: left; margin-left: 10px; width: 95px; padding: 0px;">
      <div style="float: left;">
        %</div>
      <div style="float: left;">
        <input type="text" id="input@item.CreditCardInstallmentIdValue" value="@(item.CreditCardValue.HasValue ?  item.CreditCardValue.Value.ToString("N") : "")"
          style="width: 30px; float: left; padding: 0px; margin-left: 3px; text-align: center;"
          onkeyup="setVPIKeyupData('hdn@item.CreditCardInstallmentId','@item.CreditCardInstallmentId', $(this).val(), $('#input@item.CreditCardInstallmentIdCount').val());" />
      </div>
      <div style="float: right; margin-left: 6px;">
        <a style="cursor: pointer;" title="Sil" onclick="deleteInstallment(@item.CreditCardInstallmentId);">
          <img src="/Content/Images/vcard_delete.png" /></a></div>
    </div>
  </div>
  <input type="hidden" name="VirtualPostInstallment" id="hdn@item.CreditCardInstallmentId"
    value="@item.CreditCardInstallmentId&@item.CreditCardValue&@item.CreditCardCount" />
   } 
</div>

NeoSistem.Trinnk.Management/Views/CreditCard/CreditCardList.cshtml
@model IList<CreditCard>
@{ int row = 0; }
@foreach (var item in Model)
{ 
row++;
<tr id="@("row"+item.CreditCardId)" class="@(row % 2 == 0 ? "Row" : "RowAlternate")">
  <td class="CellBegin">
    @item.CreditCardName
  </td>
    <td class="Cell">
        @if (item.Active == true) 
        {
        <span>Aktif</span> 
        }
        else
        {
        <span>Pasif</span>
        } 
    </td>
  <td class="CellEnd">
    <a href="/CreditCard/Edit/@item.CreditCardId" style="padding-bottom: 5px;">
      <div style="float: left; margin-right: 10px">
        <img src="/Content/images/edit.png" />
      </div>
    </a><a style="cursor: pointer;" onclick="DeletePost(@item.CreditCardId);">
      <div style="float: left;">
        <img src="/Content/images/delete.png" />
      </div>
    </a>
  </td>
</tr>
 } 
<tr>
  <td class="ui-state ui-state-default" colspan="7" align="right" style="border-color: #DDD;
    border-top: none; border-bottom: none;">
    <div style="float: right;" class="pagination">
     
    </div>
  </td>
</tr>

NeoSistem.Trinnk.Management/Views/CreditCard/CreditCardLog.cshtml
@model IEnumerable<NeoSistem.Trinnk.Management.Models.Entities.CreditCardLog>

@section TitleContent {

 Kredi Kartı Logları


}
@section HeadContent {

  

}

@using MvcContrib.UI.Grid
@using MvcContrib.UI.Grid.ActionSyntax
@using MvcContrib.Pagination
@using MvcContrib.UI.Pager
  <div style="width: 100%; margin: 0 auto;">
    <table cellpadding="5" cellspacing="0" class="TableList" style="width: 100%; margin-top: 5px">
      <thead>
        <tr>
        
          <td class="Header" unselectable="on">
            Kullanıcı
          </td>
          <td class="Header" unselectable="on">
            Durum
          </td>
          <td class="Header" unselectable="on">
            Sanal Pos
          </td>
          <td class="Header" unselectable="on">
            Tarih
          </td>
          <td class="Header" unselectable="on">
            IP Adresi
          </td>
          <td class="Header" unselectable="on">
            Dönen Kod
          </td>
          <td class="Header" unselectable="on">
            Detay 
          </td>
          <td class="Header" unselectable="on">
            Sipariş Tipi 
          </td>
          
          @*<td class="Header" style="width: 70px; height: 19px">
          </td>*@
        </tr>
      </thead>
      <tbody id="Tbody2">
       @{ int row = 0; }
@foreach (var item in Model)
{
    row++;
<tr id="@("row"+item.kklogid)" class="@(row % 2 == 0 ? "Row" : "RowAlternate")">
  
  <td class="CellBegin">
    @item.Store.StoreName
  </td>
  <td class="Cell">
    @item.status
  </td>
  <td class="Cell">
    @item.PosName
  </td>
  <td class="Cell">
    @String.Format("{0:g}", item.Date)
  </td>
  <td class="Cell">
    @item.IP
  </td>
  <td class="Cell">
    @item.Code
  </td>
  <td class="Cell">
    @item.Detail
  </td>
  <td class="Cell">
    @item.Ordertype
  </td>
  <td class="CellEnd">
   @* <a href="/Packet/Edit/<%: item.PacketId %>" style="padding-bottom: 5px;">
      <div style="float: left; margin-right: 10px">
        <img src="/Content/images/edit.png" />
      </div>
    </a><a style="cursor: pointer;" onclick="DeletePost(<%: item.PacketId %>);">
      <div style="float: left;">
        <img src="/Content/images/delete.png" />
      </div>
    </a>*@
  </td>
</tr>
 } 
<tr>
  <td class="ui-state ui-state-default" colspan="8" align="right" style="border-color: #DDD;
    border-top: none; border-bottom: none;">
    <div style="float: right;" class="pagination">
       @{ int sayfa=(int)ViewData["Sayfa"]; 
        int curr=(int)ViewData["Curr"];}
     <ul>
     @{for (int i = 1; i <= sayfa; i++)
       {
           <li>
           @if (i==curr)
             {
                 <a href='@Url.Action("CreditCardLog","CreditCard/",new { page=i })'><span class="currentpage">
            @i</span></a>
           
             }else{ 
            <a href='@Url.Action("CreditCardLog","CreditCard/",new { page=i })'><span >
            @i</span></a>
             }
           
           </li>
       } }
     </ul>
    </div>
  </td>
</tr>
      </tbody>
      <tfoot>
        <tr>
          <td class="ui-state ui-state-hover" colspan="8" align="right" style="border-color: #DDD;
            border-top: none; padding-right: 10px">
            Toplam Kayıt : <strong>
              @((int)ViewData["Tot"])</strong>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>

NeoSistem.Trinnk.Management/Views/CreditCard/Edit.cshtml
@model CreditCardViewModel

@section TitleContent {


}
@section HeadContent {

  <script type="text/javascript">

    function deleteInstallment(value) {
      if (confirm("Taksit işlemini silmek istediğinizden eminmisiniz ?")) {
        $.ajax({
          url: '/CreditCard/DeleteVirtualPostInstallment',
          data: { value: value, vpId: $('#vpId').val() },
          cache: false,
          success: function (data) { $('#divVirtualPostInstallment').html(data) },
          error: function (x) { alert(x.responseText) }
        });
      }
    }

    function SetVirtualPostInstallment(value, count) {
      $.ajax({
        url: '/CreditCard/SetVirtualPostInstallment',
        data: { value: value, vpId: $('#vpId').val(), count: count },
        cache: false,
        success: function (data) { $('#divVirtualPostInstallment').html(data) },
        error: function (x) { alert(x.responseText) }
      });
    }

    function setVPIKeyupData(targetControl, valOne, valTwo, count) {
      $('#' + targetControl).val(valOne + '&' + valTwo + '&' + count);
    }

  </script>

}

  @using (Html.BeginForm("Edit", "CreditCard", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
  <input type="hidden" id="vpId" value="@Model.CreditCard.CreditCardId" />
  <div style="float: left; width: 64%; padding-top: 10px; padding-left: 10px;">
    <button type="submit" style="width: 70px; height: 35px;">
      Kaydet
    </button>
    <button type="button" style="width: 70px; height: 35px;" onclick="window.location='/CreditCard/Index'">
      İptal
    </button>
    <br />
    <div style="border-bottom: dashed 1px #c0c0c0; width: 100%; height: 1px; margin-top: 15px;
      margin-bottom: 10px;">
    </div>
  </div>
  <div style="float: left;">
    <div style="float: left;">
      <table class="tableForm" style="padding-top: 10px; height: auto;">
        <tr>
          <td style="width: 120px;">
            Kredi Kartı Tanımı :
          </td>
          <td>
            @Html.TextBoxFor(model => model.CreditCard.CreditCardName, new { style = "width:300px" })
          </td>
        </tr>
          <tr>
          <td>
              Durum:
          </td>
              @{bool active = Convert.ToBoolean(Model.CreditCard.Active); }
          <td>@Html.CheckBox("CreditCard.Active",active)</td>
              </tr>
        <tr>
          <td style="width: 120px;">
            Sanal Pos :
          </td>
          <td>
            @Html.DropDownListFor(c => c.CreditCard.VirtualPosId, Model.VirtualPosItems)
          </td>
        </tr>
      </table>
    </div>
    <div style="float: left;">
      <div style="float: left; margin-top: 13px; float: left; width: 500px; margin-left: 20px;
        border-left: dashed 1px #bababa; padding-left: 20px; min-height: 70px;">
        <div style="float: left; width: 100%; padding-bottom: 10px; border-bottom: dashed 1px #bababa">
          Taksit ve Vade Farkları
        </div>
        <div style="float: left; margin-top: 10px; width: 100%;">
          <div style="float: left;">
            Taksit Sayısı:
            <input type="text" style="width: 40px;" id="txtInstallmentCount" />
          </div>
          <div style="float: left; margin-left: 5px;">
            Vade:
            <input type="text" style="width: 70px;" id="txtInstallment" />
            <button type="button" onclick="SetVirtualPostInstallment($('#txtInstallment').val(), $('#txtInstallmentCount').val());">
              Taksit Ekle
            </button>
          </div>
        </div>
        <div style="float: left; width: 349px;" id="divVirtualPostInstallment">
          @Html.Partial("CreditCardInstallmentForEdit", Model.CreditCardInstallmentItems)
        </div>
      </div>
    </div>
  </div>
  <div style="float: left; width: 100%; padding-left: 10px;">
    <div style="border-bottom: dashed 1px #c0c0c0; width: 100%; height: 1px; margin-top: 15px;
      margin-bottom: 10px;">
    </div>
    <br />
    <button type="submit" style="width: 70px; height: 35px;">
      Kaydet
    </button>
    <button type="button" style="width: 70px; height: 35px;" onclick="window.location='/CreditCard/Index'">
      İptal
    </button>
  </div>
  } 

NeoSistem.Trinnk.Management/Views/CreditCard/Index.cshtml
@model IList<CreditCard>

@section TitleContent {

  Makina Türkiye | Adres Tipi Listesi

}
@section HeadContent {

  <script type="text/javascript">
    function DeletePost(storeId) {
      if (confirm('Kaydı Silmek istediğinizden eminmisiniz ?')) {
        $.ajax({
          url: '/CreditCard/Delete',
          data: { id: storeId },
          type: 'post',
          dataType: 'json',
          success: function (data) {
            var e = data;
            if (e) {
              $('#row' + storeId).hide();
            }
            else {
              alert('Silmek hesabı kullanan paket bulunduğundan silme işlemi başarısız.');
            }
          }
        });
      }
    }
  </script>

}

  <div style="width: 100%; margin: 0 auto;">
      <p>Bu tanımlamalar iyzicoya gönderilecek taksit parametreleri için kullanılıyor. Aktif olanın taksit oranlarına göre fiyat belirlenecek.</p>
    <table cellpadding="5" cellspacing="0" class="TableList" style="width: 100%; margin-top: 5px">
      <thead>
        <tr>
          <td class="Header HeaderBegin" unselectable="on">
            Kredi Kartı Tanımı
          </td>
            <td class="Header">Durum</td>
          <td class="Header HeaderEnd" style="width: 70px; height: 19px">
          </td>
        </tr>
      </thead>
      <tbody id="table">
        @Html.Partial("CreditCardList", Model)
      </tbody>
      <tfoot>
        <tr>
          <td class="ui-state ui-state-hover" colspan="8" align="right" style="border-color: #DDD;
            border-top: none; padding-right: 10px">
            Toplam Kayıt : <strong>
              @Model.Count</strong>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>